services:
  db:
    image: postgres:latest
    container_name: postgres_blog_platform
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456!
      POSTGRES_DB: blog_platform_db
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql

volumes:
  data: