spring:
  application:
    name: BlogPlatform

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/blog_platform_db
    username: admin
    password: 123456!

  jpa:
    show-sql: true
    open-in-view: false

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect